# Nombre del microservicio
spring.application.name=account-service
server.port=8081

# Configuración de Base de Datos REACTIVA (R2DBC)z
# Nota: Usamos r2dbc:postgresql en lugar de jdbc:postgresql
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/springbank_db
spring.r2dbc.username=user
spring.r2dbc.password=password

# Inicialización automática de las tablas (Esquema)
spring.sql.init.mode=always

# Configuración de KAFKA (Cloud Stream) para 2026
# Definimos el nombre del método que procesará los eventos
spring.cloud.stream.function.definition=accountConsumer
# Destino de los eventos (el "Topic" en Kafka)
spring.cloud.stream.bindings.accountConsumer-in-0.destination=transaction-events
spring.cloud.stream.kafka.binder.brokers=localhost:9092

# Swagger / OpenAPI para WebFlux
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Logging para ver qué pasa en la DB reactiva
logging.level.org.springframework.r2dbc=DEBUG